Update codemagic.yaml

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -1,51 +1,29 @@
 workflows:
-    ios-swiftly:
-      name: ios_swiftly
-      instance_type: mac_mini_m1
-      environment:
-        vars:
-          XCODE_WORKSPACE: "swiftly.xcworkspace"
-          XCODE_SCHEME: "swiftly"
-          BUNDLE_ID: "io.codemagic.cmswiftly"
-        xcode: 14.2
-        cocoapods: default
-        ios_signing:
-          distribution_type: app_store
-          bundle_identifier: io.codemagic.cmswiftly
-      triggering:
-        events:
-          - push
-          - tag
-          - pull_request
-        branch_patterns:
-          - pattern: develop
-            include: true
-            source: true
-      scripts:
-        - name: Codemagic CLI Tools build
-          script: pip3 install codemagic-cli-tools # The Codemagic CLI tools are already installed on Codemagic servers
-        - name: Initialize Pods 
-          script: pod init && pod install
-        - name: Set up provisioning profiles settings on Xcode project
-          script: xcode-project use-profiles
-        - name: Increment build number
-          script: agvtool new-version -all $(($(app-store-connect get-latest-build-number "$APP_STORE_APPLE_ID") + 1))
-        - name: Create archive
-          script: xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME" --archive-xcargs "CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=" --archive-flags "-destination 'generic/platform=iOS' CODE_SIGNING_REQUIRED=YES CODE_SIGNING_ALLOWED=NO"
-        - name: Publish on App Store
-          script: app-store-connect publish --beta-build-localizations=@file:whats_new.json
-      artifacts:
-        - build/ios/ipa/*.ipa
-        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
-        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
-      publishing:
-         app_store_connect:
-           # Use referenced App Store Connect API key to authenticate binary upload
-           auth: integration
-           submit_to_testflight: false                     # Optional boolean, defaults to false. Whether or not to submit the uploaded build to TestFlight beta review. Required for distributing to beta groups. Note: This action is performed during post-processing.
-           # beta_groups:                                  # Specify the names of beta tester groups that will get access to the build once it has passed beta review. 
-           #      - group name 1
-           #      - group name 2                      
-         email:
-           recipients:
-            - user_1@example.com
+  my-workflow:
+    scripts:
+      - name: Add provisioning profiles
+        script: |
+          set -e # exit on first failed command
+
+          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
+          mkdir -p "$PROFILES_HOME"
+          echo ${PROVISIONING_PROFILE?} | base64 --decode > "$PROFILES_HOME/$(uuidgen).mobileprovision"
+      - name: Add signing certificate
+        script: |
+          set -e # exit on first failed command
+
+          echo ${CERTIFICATE?} | base64 --decode > /tmp/certificate.p12
+          keychain initialize
+          keychain add-certificates \
+              --certificate /tmp/certificate.p12 \
+              --certificate-password ${CERTIFICATE_PASSWORD?}
+      - name: Increment build number
+        script: agvtool new-version -all $BUILD_NUMBER
+      - name: Set up code signing settings on Xcode project
+        script: xcode-project use-profiles
+      - name: Build ipa for distribution
+        script: xcode-project build-ipa \
+                    --workspace "${XCODE_WORKSPACE?}" \
+                    --scheme "${XCODE_SCHEME?}"
+    artifacts:
+      - build/ios/ipa/*.ipa
