Update codemagic.yaml

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -3,14 +3,14 @@ workflows:
     scripts:
       - name: Add provisioning profiles
         script: |
-          set -e # exit on first failed command
+          # set -e # exit on first failed command
 
           PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
           mkdir -p "$PROFILES_HOME"
           echo ${PROVISIONING_PROFILE?} | base64 --decode > "$PROFILES_HOME/$(uuidgen).mobileprovision"
       - name: Add signing certificate
         script: |
-          set -e # exit on first failed command
+          # set -e # exit on first failed command
 
           echo ${CERTIFICATE?} | base64 --decode > /tmp/certificate.p12
           keychain initialize
